/* INSERT SEATS */
DECLARE @COL INT
DECLARE @ROW INT
DECLARE @ROOM INT
DECLARE @STRCOL VARCHAR
DECLARE @STRROOM VARCHAR

SET @COL = 1
SET @ROW = 1
SET @ROOM = 13
WHILE @ROOM <= 20
BEGIN
	IF @ROOM < 10 SET @STRROOM = '0' ELSE SET @STRROOM = ''
	WHILE @ROW <= 10
	BEGIN
		WHILE @COL <= 12
		BEGIN
			IF @COL < 10 SET @STRCOL = '0' ELSE SET @STRCOL = ''
			INSERT INTO Seat VALUES (
				'RM0' + @STRROOM + CONVERT(char, @ROOM),
				'CLASS1',
				CHAR(64 + @ROW) + @STRCOL + CONVERT(varchar, @COL)
			)
			SET @COL = @COL + 1
		END
		SET @ROW = @ROW + 1
		SET @COL = 1
	END
	SET @ROOM = @ROOM + 1
	SET @ROW = 1
END

/* INSERT CINE_MOVIE DETAILS */
DECLARE @MOVIEID INT
DECLARE @CINEIX INT

SET @MOVIEID = 1
SET @CINEIX = 1

WHILE @CINEIX <= 4
BEGIN
	WHILE @MOVIEID <= 12
	BEGIN
		INSERT INTO Cine_MovieDetails VALUES(@MOVIEID, 'CINE' + CONVERT(VARCHAR, @CINEIX), 14, GETDATE())
		SET @MOVIEID = @MOVIEID + 1
	END
	SET @MOVIEID = 1
	SET @CINEIX = @CINEIX + 1
END

DBCC CHECKIDENT (Schedule, RESEED, 0)

/* INSERT SEAT_SHOW DETAILS */

DECLARE @SEATID INT
DECLARE @SCH INT

SET @SCH = 74
SET @SEATID = 1081

WHILE @SCH <= 82
BEGIN
	WHILE @SEATID <= 1200
	BEGIN
		INSERT INTO Seat_ShowDetails VALUES (NULL, 
			@SCH,
			@SEATID,
			'False',
			'False'
		)
		SET @SEATID = @SEATID + 1
	END
	SET @SEATID = 1081
	SET @SCH = @SCH + 1
END

/* INSERT SCHEDULES */
DECLARE @DATE DATE
DECLARE @MOVIELENGTH INT
DECLARE @STARTTIME TIME
DECLARE	@CINE_MOVIEID INT
DECLARE @ROOM INT

WHILE @
BEGIN

END

SET IDENTITY_INSERT Schedule ON