DECLARE @COL INT
DECLARE @ROW INT
DECLARE @ROOM INT
DECLARE @STRCOL VARCHAR
DECLARE @STRROOM VARCHAR

SET @COL = 1
SET @ROW = 1
SET @ROOM = 1
WHILE @ROOM <= 12
BEGIN
	IF @ROOM < 10 SET @STRROOM = '0' ELSE SET @STRROOM = ''
	WHILE @ROW <= 10
	BEGIN
		WHILE @COL <= 12
		BEGIN
			IF @COL < 10 SET @STRCOL = '0' ELSE SET @STRCOL = ''
			INSERT INTO Seat VALUES (
				'RM0' + @STRROOM + CONVERT(char, @ROOM),
				'CLASS1',
				CHAR(64 + @ROW) + @STRCOL + CONVERT(varchar, @COL)
			)
			SET @COL = @COL + 1
		END
		SET @ROW = @ROW + 1
		SET @COL = 1
	END
	SET @ROOM = @ROOM + 1
	SET @ROW = 1
END

DECLARE @COL INT
DECLARE @ROW INT
DECLARE @SCH INT
DECLARE @STRCOL VARCHAR

SET @SCH = 2
SET @ROW = 1
SET @COL = 1
WHILE @SCH <= 9
BEGIN
	WHILE @ROW <= 10
	BEGIN
		WHILE @COL <= 12
		BEGIN
			IF @COL < 10 SET @STRCOL = '0' ELSE SET @STRCOL = ''
			INSERT INTO Seat_ShowDetails VALUES (NULL, 
				@SCH,
				'S02' + CHAR(64 + @ROW) + @STRCOL + CONVERT(varchar, @COL),
				'False',
				'False'
			)
			SET @COL = @COL + 1
		END
		SET @ROW = @ROW + 1
		SET @COL = 1
	END
	SET @SCH = @SCH + 1
	SET @ROW = 1
END
