//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccount
    {
        public int AdminAccountID { get; set; }
        public string Section { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Role Role { get; set; }
    }
}
