//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHeader
    {
        public BookingHeader()
        {
            this.Seat_ShowDetails = new HashSet<Seat_ShowDetails>();
        }
    
        public int HeaderID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string SessionID { get; set; }
        public Nullable<bool> Took { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> ReservedTime { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<Seat_ShowDetails> Seat_ShowDetails { get; set; }
    }
}
