//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public Cinema()
        {
            this.Cine_MovieDetails = new HashSet<Cine_MovieDetails>();
            this.CinemaImages = new HashSet<CinemaImage>();
            this.Rooms = new HashSet<Room>();
        }
    
        public string CinemaID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Cine_MovieDetails> Cine_MovieDetails { get; set; }
        public virtual ICollection<CinemaImage> CinemaImages { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
