//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member {
        public Member() {
            this.BookingHeaders = new HashSet<BookingHeader>();
        }

        public int MemberID { get; set; }

        [Display(Name = "Chứng minh nhân dân")]
        [RegularExpression("\\d{9}", ErrorMessage = "Số CMND không đúng định dạng")]
        [Required(ErrorMessage = "Bạn phải nhập số CMND.")]
        public string IDCardNumber { get; set; }

        [Display(Name = "Tên")]
        [Required]
        public string Firstname { get; set; }

        [Display(Name = "Họ")]
        [Required]
        public string Lastname { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Định dạng email không đúng.")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Mật khẩu")]
        [MinLength(9, ErrorMessage = "Mật khẩu phải dài hơn hoặc bằng 9 kí tự")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Số điện thoại")]
        [RegularExpression("^[0]\\d{9,10}$", ErrorMessage = "Số điện thoại không đúng định dạng")]
        [Required(ErrorMessage = "Bạn phải nhập số điện thoại.")]
        public string Phone { get; set; }

        [Display(Name = "Địa chỉ")]
        [Required]
        public string Address { get; set; }


        public Nullable<int> RoleID { get; set; }

        [Display(Name = "Giới tính")]
        [Required]
        public Nullable<bool> Gender { get; set; }

        [Display(Name = "Ngày sinh")]
        [Required]
        [DataType(DataType.DateTime)]
        [Range(typeof(DateTime), "1/1/1920", "1/1/2005")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Birthday { get; set; }
        public string AvatarURL { get; set; }

        public virtual ICollection<BookingHeader> BookingHeaders { get; set; }
        public virtual Role Role { get; set; }
    }
}
