//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Cine_MovieDetails = new HashSet<Cine_MovieDetails>();
            this.MovieEditions = new HashSet<MovieEdition>();
            this.MovieGenres = new HashSet<MovieGenre>();
        }
    
        public int MovieID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> MovieLength { get; set; }
        public string Director { get; set; }
        public string Actors { get; set; }
        public string ThumbnailURL { get; set; }
        public string TrailerURL { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<System.DateTime> BeginShowDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string AgeLimitationID { get; set; }
        public string LongDescription { get; set; }
        public string WideThumbnail { get; set; }
        public Nullable<bool> HotMovie { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual AgeLimitation AgeLimitation { get; set; }
        public virtual ICollection<Cine_MovieDetails> Cine_MovieDetails { get; set; }
        public virtual ICollection<MovieEdition> MovieEditions { get; set; }
        public virtual ICollection<MovieGenre> MovieGenres { get; set; }
    }
}
