//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promote
    {
        public Promote()
        {
            this.Schedules = new HashSet<Schedule>();
            this.Cinemas = new HashSet<Cinema>();
        }
    
        public int PromoteID { get; set; }
        public Nullable<int> PriceOff { get; set; }
        public Nullable<int> NewsID { get; set; }
        public string Title { get; set; }
        public Nullable<int> FixedDayOfWeek { get; set; }
        public Nullable<System.DateTime> BeginDay { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual News News { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Cinema> Cinemas { get; set; }
    }
}
