//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Schedules = new HashSet<Schedule>();
            this.Seats = new HashSet<Seat>();
        }
    
        public string RoomID { get; set; }
        public string CinemaID { get; set; }
        public string Name { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
