//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat_ShowDetails
    {
        public Nullable<int> BookingHeaderID { get; set; }
        public int ScheduleID { get; set; }
        public int SeatID { get; set; }
        public Nullable<bool> Reserved { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual BookingHeader BookingHeader { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
