//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtitle
    {
        public Subtitle()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int SubtitleID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
